from fpdf import FPDF
from datetime import datetime


def _safe(text: str) -> str:
    """Strip/replace characters outside latin-1 so Helvetica doesn't choke."""
    return (
        text
        .replace('—', '-').replace('–', '-')
        .replace('’', "'").replace('‘', "'")
        .replace('“', '"').replace('”', '"')
        .replace('•', '*').replace('…', '...')
        .replace('–', '-').replace('â', "'")
        .encode('latin-1', errors='replace').decode('latin-1')
    )


# Colour palette (RGB)
C_BG = (15, 23, 42)          # slate-950
C_CARD = (30, 41, 59)        # slate-800
C_ACCENT = (139, 92, 246)    # violet-500
C_GREEN = (52, 211, 153)     # emerald-400
C_BLUE = (96, 165, 250)      # blue-400
C_YELLOW = (251, 191, 36)    # amber-400
C_RED = (248, 113, 113)      # red-400
C_WHITE = (255, 255, 255)
C_MUTED = (148, 163, 184)    # slate-400
C_FAINT = (71, 85, 105)      # slate-600


def _score_color(s: int) -> tuple[int, int, int]:
    if s >= 75:
        return C_GREEN
    if s >= 50:
        return C_BLUE
    if s >= 25:
        return C_YELLOW
    return C_RED


def _score_label(s: int) -> str:
    if s >= 80:
        return "Elite Developer Profile"
    if s >= 65:
        return "Strong Developer Profile"
    if s >= 50:
        return "Developing Profile"
    if s >= 35:
        return "Emerging Developer"
    return "Needs Attention"


class DevScopePDF(FPDF):

    def header(self):
        # Dark header bar
        self.set_fill_color(*C_BG)
        self.rect(0, 0, 210, 22, style="F")
        self.set_font("Helvetica", "B", 13)
        self.set_text_color(*C_ACCENT)
        self.set_xy(14, 6)
        self.cell(60, 10, "DevScope", ln=False)
        self.set_font("Helvetica", "", 9)
        self.set_text_color(*C_MUTED)
        self.set_xy(80, 8)
        self.cell(0, 6, "AI Developer Career Report", ln=False, align="L")
        self.set_xy(0, 8)
        self.cell(196, 6, datetime.now().strftime("%B %d, %Y"), ln=False, align="R")
        self.ln(18)

    def footer(self):
        self.set_y(-14)
        self.set_font("Helvetica", "", 8)
        self.set_text_color(*C_FAINT)
        self.cell(0, 8, _safe(f"Page {self.page_no()} - Generated by DevScope"), align="C")

    def section_title(self, text: str, color: tuple[int, int, int] = C_ACCENT):
        self.set_font("Helvetica", "B", 11)
        self.set_text_color(*color)
        self.ln(4)
        self.cell(0, 7, text, ln=True)
        # Underline
        x, y = self.get_x(), self.get_y()
        self.set_draw_color(*color)
        self.set_line_width(0.5)
        self.line(14, y, 196, y)
        self.ln(3)

    def score_badge(self, label: str, score: int, x: float, y: float, w: float = 44):
        color = _score_color(score)
        self.set_fill_color(*C_CARD)
        self.rect(x, y, w, 22, style="F")
        self.set_font("Helvetica", "B", 16)
        self.set_text_color(*color)
        self.set_xy(x, y + 2)
        self.cell(w, 10, str(score), align="C", ln=False)
        self.set_font("Helvetica", "", 7)
        self.set_text_color(*C_MUTED)
        self.set_xy(x, y + 13)
        self.cell(w, 6, label, align="C", ln=False)

    def bullet_list(self, items: list[str], bullet: str = "•", color: tuple[int, int, int] = C_MUTED):
        for item in items:
            self.set_font("Helvetica", "", 9)
            self.set_text_color(*color)
            self.set_x(18)
            self.cell(5, 6, _safe(bullet), ln=False)
            self.set_text_color(*C_WHITE)
            self.multi_cell(0, 6, _safe(item), ln=True)
            if self.get_y() > 270:
                self.add_page()


def generate_report(data: dict) -> bytes:
    github = data.get("github")
    resume = data.get("resume")
    portfolio = data.get("portfolio")

    # Career score (weighted)
    pairs = []
    if github:
        pairs.append((github["overallScore"], 0.35))
    if resume:
        pairs.append((resume["overallScore"], 0.45))
    if portfolio:
        pairs.append((portfolio["overallScore"], 0.20))
    total_w = sum(w for _, w in pairs)
    career_score = round(sum(s * w for s, w in pairs) / total_w) if pairs else 0

    pdf = DevScopePDF(orientation="P", unit="mm", format="A4")
    pdf.set_auto_page_break(auto=True, margin=16)
    pdf.set_margins(14, 14, 14)
    pdf.set_fill_color(*C_BG)
    pdf.set_text_color(*C_WHITE)

    # ── Page 1: Career overview ──────────────────────────────────────────────
    pdf.add_page()
    pdf.set_fill_color(*C_BG)
    pdf.rect(0, 0, 210, 297, style="F")

    # Hero
    pdf.set_font("Helvetica", "B", 24)
    pdf.set_text_color(*C_WHITE)
    pdf.ln(4)
    pdf.cell(0, 12, "Career Analysis Report", ln=True, align="C")

    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(*C_MUTED)
    pdf.cell(0, 7, _score_label(career_score), ln=True, align="C")
    pdf.ln(6)

    # Big career score box
    pdf.set_fill_color(*C_CARD)
    pdf.rect(55, pdf.get_y(), 100, 36, style="F")
    pdf.set_font("Helvetica", "B", 36)
    pdf.set_text_color(*_score_color(career_score))
    pdf.set_xy(55, pdf.get_y() + 4)
    pdf.cell(100, 18, str(career_score), align="C", ln=False)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(*C_MUTED)
    pdf.set_xy(55, pdf.get_y() + 22)
    pdf.cell(100, 8, "Overall Career Score  (out of 100)", align="C", ln=False)
    pdf.ln(46)

    # Module score badges
    done_count = sum(1 for x in [github, resume, portfolio] if x)
    if done_count > 0:
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(*C_MUTED)
        pdf.cell(0, 6, f"{done_count} of 3 modules analysed", ln=True, align="C")
        pdf.ln(4)

        badge_y = pdf.get_y()
        bx = 14.0
        badge_w = 56.0
        if github:
            pdf.score_badge("GitHub", github["overallScore"], bx, badge_y, badge_w)
        if resume:
            pdf.score_badge("Resume", resume["overallScore"], bx + 64, badge_y, badge_w)
        if portfolio:
            pdf.score_badge("Portfolio", portfolio["overallScore"], bx + 128, badge_y, badge_w)
        pdf.ln(32)

    # ── GitHub Section ───────────────────────────────────────────────────────
    if github:
        pdf.section_title("GitHub Analysis", C_ACCENT)

        sub_y = pdf.get_y()
        pdf.score_badge("Profile", github.get("profileScore", 0), 14, sub_y, 40)
        pdf.score_badge("Repos", github.get("repositoryScore", 0), 58, sub_y, 40)
        pdf.score_badge("Docs", github.get("documentationScore", 0), 102, sub_y, 40)
        pdf.score_badge("Diversity", github.get("diversityScore", 0), 146, sub_y, 40)
        pdf.ln(30)

        if github.get("summary"):
            pdf.set_font("Helvetica", "I", 9)
            pdf.set_text_color(*C_MUTED)
            pdf.multi_cell(0, 6, _safe(github["summary"]), ln=True)
            pdf.ln(2)

        if github.get("strengths"):
            pdf.set_font("Helvetica", "B", 9)
            pdf.set_text_color(*C_GREEN)
            pdf.cell(0, 6, "Strengths", ln=True)
            pdf.bullet_list(github["strengths"][:4], "+", C_GREEN)

        if github.get("suggestions"):
            pdf.ln(2)
            pdf.set_font("Helvetica", "B", 9)
            pdf.set_text_color(*C_YELLOW)
            pdf.cell(0, 6, "Improvements", ln=True)
            pdf.bullet_list(github["suggestions"][:4], ">", C_YELLOW)

    # ── Resume Section ───────────────────────────────────────────────────────
    if resume:
        if pdf.get_y() > 220:
            pdf.add_page()
            pdf.set_fill_color(*C_BG)
            pdf.rect(0, 0, 210, 297, style="F")

        pdf.section_title("Resume Analysis", C_BLUE)

        sub_y = pdf.get_y()
        pdf.score_badge("ATS", resume.get("atsScore", 0), 14, sub_y, 40)
        pdf.score_badge("Technical", resume.get("technicalScore", 0), 58, sub_y, 40)
        pdf.score_badge("Readability", resume.get("readabilityScore", 0), 102, sub_y, 40)
        pdf.score_badge("Grammar", resume.get("grammarScore", 0), 146, sub_y, 40)
        pdf.ln(30)

        if resume.get("summary"):
            pdf.set_font("Helvetica", "I", 9)
            pdf.set_text_color(*C_MUTED)
            pdf.multi_cell(0, 6, _safe(resume["summary"]), ln=True)
            pdf.ln(2)

        if resume.get("strengths"):
            pdf.set_font("Helvetica", "B", 9)
            pdf.set_text_color(*C_GREEN)
            pdf.cell(0, 6, "Strengths", ln=True)
            pdf.bullet_list(resume["strengths"][:4], "+", C_GREEN)

        if resume.get("improvements"):
            pdf.ln(2)
            pdf.set_font("Helvetica", "B", 9)
            pdf.set_text_color(*C_YELLOW)
            pdf.cell(0, 6, "Improvements", ln=True)
            pdf.bullet_list(resume["improvements"][:4], ">", C_YELLOW)

        if resume.get("missingKeywords"):
            pdf.ln(2)
            pdf.set_font("Helvetica", "B", 9)
            pdf.set_text_color(*C_RED)
            pdf.cell(0, 6, "Missing Keywords", ln=True)
            kws = _safe(", ".join(resume["missingKeywords"][:8]))
            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(*C_MUTED)
            pdf.set_x(18)
            pdf.multi_cell(0, 6, kws, ln=True)

    # ── Portfolio Section ────────────────────────────────────────────────────
    if portfolio:
        if pdf.get_y() > 220:
            pdf.add_page()
            pdf.set_fill_color(*C_BG)
            pdf.rect(0, 0, 210, 297, style="F")

        pdf.section_title("Portfolio Analysis", (52, 211, 153))  # emerald

        sub_y = pdf.get_y()
        pdf.score_badge("UX", portfolio.get("uxScore", 0), 14, sub_y, 40)
        pdf.score_badge("Accessibility", portfolio.get("accessibilityScore", 0), 58, sub_y, 40)
        pdf.score_badge("SEO", portfolio.get("seoScore", 0), 102, sub_y, 40)
        pdf.score_badge("Content", portfolio.get("contentScore", 0), 146, sub_y, 40)
        pdf.ln(30)

        if portfolio.get("url"):
            pdf.set_font("Helvetica", "", 8)
            pdf.set_text_color(*C_MUTED)
            pdf.cell(0, 5, _safe(f"Analysed: {portfolio['url']}"), ln=True)
            pdf.ln(2)

        if portfolio.get("summary"):
            pdf.set_font("Helvetica", "I", 9)
            pdf.set_text_color(*C_MUTED)
            pdf.multi_cell(0, 6, _safe(portfolio["summary"]), ln=True)
            pdf.ln(2)

        if portfolio.get("strengths"):
            pdf.set_font("Helvetica", "B", 9)
            pdf.set_text_color(*C_GREEN)
            pdf.cell(0, 6, "Strengths", ln=True)
            pdf.bullet_list(portfolio["strengths"][:4], "+", C_GREEN)

        if portfolio.get("suggestions"):
            pdf.ln(2)
            pdf.set_font("Helvetica", "B", 9)
            pdf.set_text_color(*C_YELLOW)
            pdf.cell(0, 6, "Recommendations", ln=True)
            pdf.bullet_list(portfolio["suggestions"][:5], ">", C_YELLOW)

    return bytes(pdf.output())
